(function(){var aa=' coordorigin="0 0" coordsize="',ba=' endcap="flat"',D=" l ",H=" m ",ca='"><g_vml_:fill color="',da=":0;width:",fa='<g_vml_:shape fillcolor="',ha="borderRadius_bl",ia="borderRadius_br",ja="borderRadius_tl",ka="borderRadius_tr",la="borderWidth_bottom",oa="borderWidth_left",pa="borderWidth_right",qa="borderWidth_top",ra="function",J="none",va="object",wa="rgba(",xa="shadowBlurRadius",ya='style="position:absolute;top:0;',L="transparent",za="{borderColor}",Aa="{borderWidth}",M,Ba=this||self,Ca=
function(a){return"string"==typeof a},Da=function(a,b,e){a=a.split(".");e=e||Ba;a[0]in e||"undefined"==typeof e.execScript||e.execScript("var "+a[0]);for(var c;a.length&&(c=a.shift());)a.length||void 0===b?e=e[c]&&e[c]!==Object.prototype[c]?e[c]:e[c]={}:e[c]=b},Ea=function(){},Fa=function(a){var b=typeof a;if(b==va)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var e=Object.prototype.toString.call(a);if("[object Window]"==e)return va;if("[object Array]"==e||"number"==typeof a.length&&
"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==e||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return ra}else return"null";else if(b==ra&&"undefined"==typeof a.call)return va;return b},Ga=function(a){var b=typeof a;return b==va&&null!=a||b==ra},N=function(a){return a[Ha]||(a[Ha]=++Ia)},Ha="closure_uid_"+(1E9*Math.random()>>>0),Ia=0,Ja=function(a,
b){function e(){}e.prototype=b.prototype;a.pa=b.prototype;a.prototype=new e;a.prototype.constructor=a;a.qa=function(c,d,h){for(var p=Array(arguments.length-2),n=2;n<arguments.length;n++)p[n-2]=arguments[n];return b.prototype[d].apply(c,p)}};var Ka;var La=Array.prototype.indexOf?function(a,b,e){return Array.prototype.indexOf.call(a,b,e)}:function(a,b,e){e=null==e?0:0>e?Math.max(0,a.length+e):e;if(Ca(a))return Ca(b)&&1==b.length?a.indexOf(b,e):-1;for(;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},Ma=Array.prototype.forEach?function(a,b,e){Array.prototype.forEach.call(a,b,e)}:function(a,b,e){for(var c=a.length,d=Ca(a)?a.split(""):a,h=0;h<c;h++)h in d&&b.call(e,d[h],h,a)};var Na=function(){return!0};var Oa=function(){};Oa.prototype.g=function(){return this};(new Oa).g("");var R=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Pa=function(a,b){return a<b?-1:a>b?1:0};var Qa=function(){};Qa.prototype.g=function(){return this};(new Qa).g("");var Ra=function(){};Ra.prototype.g=function(){return this};(new Ra).g("");var S;a:{var Sa=Ba.navigator;if(Sa){var Ta=Sa.userAgent;if(Ta){S=Ta;break a}}S=""};var Ua=function(){};Ua.prototype.g=function(){return this};(new Ua).g("<!DOCTYPE html>",0);(new Ua).g("",0);(new Ua).g("<br>",0);var Va,Wa,Xa,Ya,Za,$a=function(a){this.N=a;this.C=!1},ab=/background-color/i,bb=/^background-image/i,cb=/background/i,db=/goog-ms-box-shadow/i,eb=/goog-ms-border-radius/i,fb=/goog-ms-border-bottom-left-radius/i,gb=/goog-ms-border-bottom-right-radius/i,hb=/goog-ms-border-top-left-radius/i,ib=/goog-ms-border-top-right-radius/i,jb=/opacity/i,kb=/^border:/i,lb=/^border-style:/i,mb=/^border-color:/i,nb=/^border-left:/i,pb=/^border-right:/i,qb=/^border-top:/i,rb=/^border-bottom:/i,sb=/^border-left-style:/i,
tb=/^border-right-style:/i,ub=/^border-top-style:/i,vb=/^border-bottom-style:/i,wb=/^border-left-color:/i,xb=/^border-right-color:/i,yb=/^border-top-color:/i,zb=/^border-bottom-color:/i,Ab=/^border-width:/i,Bb=/:hover/i,Cb=/^#?([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?$/,Db=/^\-?[0-9]+(\.[0-9]+)?px$/,Eb=/^\-?[0-9]+(\.[0-9]+)?$/,Fb=/[^\s]+/g,Gb=/none|dotted|dashed|solid|double|groove|ridge|inset|outset/i,Hb=/^margin:|margin-top:|margin-bottom:|margin-left:|margin-right:/i,Ib=/top|bottom|left|right|center/i,
Jb=[db,fb,gb,hb,ib,eb],Kb=[db,fb,gb,hb,ib,eb];M=$a.prototype;M.U=function(){for(var a=0;a<Jb.length;a++)if(Jb[a].test(this.N))return!0;return!1};M.ma=function(){for(var a=0;a<Kb.length;a++)if(Kb[a].test(this.N))return!0;return!1};M.b=function(a){if(!a||!a.indexOf)return a;-1!=a.indexOf(":")&&(a=a.split(":")[1]);if("medium"==R(a))return null;-1!=a.indexOf("px")&&(a=a.substr(0,a.length-2));return parseFloat(a)};
M.parse=function(){for(var a={},b=this.N.split(";"),e=0;e<b.length;e++){var c=R(b[e]);hb.test(c)?a.borderRadius_tl=this.b(c):fb.test(c)?a.borderRadius_bl=this.b(c):gb.test(c)?a.borderRadius_br=this.b(c):ib.test(c)&&(a.borderRadius_tr=this.b(c));if(eb.test(c)){var d=R(c.split(":")[1]);d=this.ka(d);for(var h in d)a[h]=d[h]}else if(jb.test(c))d=c.split(":")[1],a.opacity=parseFloat(d);else if(db.test(c))c=c.split(":")[1].match(Fb),a.shadowHOffs=this.b(c[0]),a.shadowVOffs=this.b(c[1]),a.shadowBlurRadius=
this.b(c[2]),a.shadowColor=c.slice(3,c.length).join(" ");else if(Ab.test(c))d=R(c.split(":")[1]),c=d.split(" "),1==c.length&&(d=this.b(c[0]),a.borderWidth_left=d,a.borderWidth_right=d,a.borderWidth_top=d,a.borderWidth_bottom=d);else if(nb.test(c))for(c in d=R(c.split(":")[1]),d=this.m(d),d)a[c+"_left"]=d[c];else if(pb.test(c))for(c in d=R(c.split(":")[1]),d=this.m(d),d)a[c+"_right"]=d[c];else if(qb.test(c))for(c in d=R(c.split(":")[1]),d=this.m(d),d)a[c+"_top"]=d[c];else if(rb.test(c))for(c in d=
R(c.split(":")[1]),d=this.m(d),d)a[c+"_bottom"]=d[c];else if(ab.test(c))d=R(c.split(":")[1]),a.backgroundColor=d;else if(bb.test(c))d=R(c.substr(c.indexOf(":")+1)),a.backgroundImageUrl=d.substring(4,d.lastIndexOf(")"));else if(cb.test(c))for(h in d=c.substring(11,c.length),d=this.ja(d),d)a[h]=d[h];else if(mb.test(c))d=R(c.split(":")[1]),c=d.split(" "),4==c.length&&-1==d.indexOf(wa)?(a.borderColor_top=c[0],a.borderColor_right=c[1],a.borderColor_bottom=c[2],a.borderColor_left=c[3]):(a.borderColor_top=
d,a.borderColor_right=d,a.borderColor_bottom=d,a.borderColor_left=d);else if(wb.test(c))d=R(c.split(":")[1]),a.borderColor_left=d;else if(xb.test(c))d=R(c.split(":")[1]),a.borderColor_right=d;else if(yb.test(c))d=R(c.split(":")[1]),a.borderColor_top=d;else if(zb.test(c))d=R(c.split(":")[1]),a.borderColor_bottom=d;else if(kb.test(c))for(h in d=R(c.split(":")[1]),d=this.m(d),d)a[h+"_top"]=d[h],a[h+"_left"]=d[h],a[h+"_bottom"]=d[h],a[h+"_right"]=d[h];else Hb.test(c)?this.C=!0:lb.test(c)?(d=R(c.split(":")[1]),
a.borderStyle_top=d,a.borderStyle_left=d,a.borderStyle_bottom=d,a.borderStyle_right=d):ub.test(c)?(d=R(c.split(":")[1]),a.borderStyle_top=d):sb.test(c)?(d=R(c.split(":")[1]),a.borderStyle_left=d):vb.test(c)?(d=R(c.split(":")[1]),a.borderStyle_bottom=d):tb.test(c)&&(d=R(c.split(":")[1]),a.borderStyle_right=d)}return a};
M.ka=function(a){var b=a.split(" ");a={};1==b.length?(b=this.b(b[0]),a.borderRadius_tl=b,a.borderRadius_bl=b,a.borderRadius_br=b,a.borderRadius_tr=b):4==b.length&&(a.borderRadius_tl=this.b(b[0]),a.borderRadius_tr=this.b(b[1]),a.borderRadius_br=this.b(b[2]),a.borderRadius_bl=this.b(b[3]));return a};
M.ja=function(a){for(var b=a.split(" "),e={},c=0;c<b.length;c++){var d=R(b[c]);d==L?e.backgroundColor=d:Cb.test(d)?e.backgroundColor=d:0==d.indexOf(wa)?(d=a.indexOf(wa),e.backgroundColor=a.substr(d,a.indexOf(")",d)-d+1)):0==d.indexOf("url(")?e.backgroundImageUrl=d.substring(4,d.lastIndexOf(")")):Ib.test(d)&&(e.backgroundPosition=d)}return e};
M.m=function(a){for(var b=a.split(" "),e={},c=0;c<b.length;c++){var d=R(b[c]);d==L?e.borderColor=d:Cb.test(d)?e.borderColor=d:0==d.indexOf(wa)?(d=a.indexOf(wa),e.borderColor=a.substring(d,a.indexOf(")",d)+1)):Cb.test(b[c])?e.borderColor=b[c]:Eb.test(b[c])?e.borderWidth=parseFloat(b[c]):Db.test(b[c])?e.borderWidth=this.b(b[c]):Gb.test(b[c])?e.borderStyle=b[c]:/[a-zA-Z]+/.test(b[c])&&(e.borderColor=b[c])}return e};var Lb=function(a){Lb[" "](a);return a};Lb[" "]=Ea;var Mb=function(a,b,e,c){c=c?c(b):b;return Object.prototype.hasOwnProperty.call(a,c)?a[c]:a[c]=e(b)};var Nb=-1!=S.indexOf("Opera"),Ob=-1!=S.indexOf("Trident")||-1!=S.indexOf("MSIE"),Pb=-1!=S.indexOf("Edge"),Qb=-1!=S.indexOf("Gecko")&&!(-1!=S.toLowerCase().indexOf("webkit")&&-1==S.indexOf("Edge"))&&!(-1!=S.indexOf("Trident")||-1!=S.indexOf("MSIE"))&&-1==S.indexOf("Edge"),Rb=-1!=S.toLowerCase().indexOf("webkit")&&-1==S.indexOf("Edge"),Sb=function(){var a=Ba.document;return a?a.documentMode:void 0},Tb;
a:{var Ub="",Vb=function(){var a=S;if(Qb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Pb)return/Edge\/([\d\.]+)/.exec(a);if(Ob)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Rb)return/WebKit\/(\S+)/.exec(a);if(Nb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Vb&&(Ub=Vb?Vb[1]:"");if(Ob){var ec=Sb();if(null!=ec&&ec>parseFloat(Ub)){Tb=String(ec);break a}}Tb=Ub}
var fc=Tb,gc={},hc=function(a){return Mb(gc,a,function(){for(var b=0,e=R(String(fc)).split("."),c=R(String(a)).split("."),d=Math.max(e.length,c.length),h=0;0==b&&h<d;h++){var p=e[h]||"",n=c[h]||"";do{p=/(\d*)(\D*)(.*)/.exec(p)||["","","",""];n=/(\d*)(\D*)(.*)/.exec(n)||["","","",""];if(0==p[0].length&&0==n[0].length)break;b=Pa(0==p[1].length?0:parseInt(p[1],10),0==n[1].length?0:parseInt(n[1],10))||Pa(0==p[2].length,0==n[2].length)||Pa(p[2],n[2]);p=p[3];n=n[3]}while(0==b)}return 0<=b})},ic;
ic=Ba.document&&Ob?Sb():void 0;var jc=!Ob||9<=Number(ic),kc=Ob&&!hc("9"),lc=function(){if(!Ba.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{Ba.addEventListener("test",Ea,b),Ba.removeEventListener("test",Ea,b)}catch(e){}return a}();var mc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Y=!1};mc.prototype.preventDefault=function(){this.defaultPrevented=!0};var nc=function(a,b){mc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.keyCode=0;this.ctrlKey=!1;this.R=null;a&&this.ha(a,b)};Ja(nc,mc);
nc.prototype.ha=function(a,b){var e=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(Qb){a:{try{Lb(b.nodeName);var c=!0;break a}catch(d){}c=!1}c||(b=null)}}else"mouseover"==e?b=a.fromElement:"mouseout"==e&&(b=a.toElement);this.relatedTarget=b;this.keyCode=a.keyCode||0;this.ctrlKey=a.ctrlKey;this.R=a;a.defaultPrevented&&this.preventDefault()};
nc.prototype.preventDefault=function(){nc.pa.preventDefault.call(this);var a=this.R;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,kc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var oc="closure_listenable_"+(1E6*Math.random()|0),pc=0;var qc=function(a,b,e,c,d,h){this.listener=a;this.proxy=b;this.src=e;this.type=c;this.capture=!!d;this.K=h;++pc;this.o=this.H=!1};qc.prototype.X=function(){this.o=!0;this.K=this.src=this.proxy=this.listener=null};var rc=function(a){this.src=a;this.i={};this.O=0};rc.prototype.add=function(a,b,e,c,d){var h=a.toString();a=this.i[h];a||(a=this.i[h]=[],this.O++);var p;a:{for(p=0;p<a.length;++p){var n=a[p];if(!n.o&&n.listener==b&&n.capture==!!c&&n.K==d)break a}p=-1}-1<p?(b=a[p],e||(b.H=!1)):(b=new qc(b,null,this.src,h,!!c,d),b.H=e,a.push(b));return b};
rc.prototype.la=function(a){var b=a.type;if(!(b in this.i))return!1;var e=this.i[b],c=La(e,a),d;(d=0<=c)&&Array.prototype.splice.call(e,c,1);d&&(a.X(),0==this.i[b].length&&(delete this.i[b],this.O--));return d};var sc="closure_lm_"+(1E6*Math.random()|0),tc={},uc=0,wc=function(a,b,e,c,d){if(c&&c.once)return vc(a,b,e,c,d);if("array"==Fa(b)){for(var h=0;h<b.length;h++)wc(a,b[h],e,c,d);return null}e=xc(e);return a&&a[oc]?a.va(b,e,Ga(c)?!!c.capture:!!c,d):yc(a,b,e,!1,c,d)},yc=function(a,b,e,c,d,h){if(!b)throw Error("Invalid event type");var p=Ga(d)?!!d.capture:!!d,n=zc(a);n||(a[sc]=n=new rc(a));e=n.add(b,e,c,p,h);if(e.proxy)return e;c=Ac();e.proxy=c;c.src=a;c.listener=e;if(a.addEventListener)lc||(d=p),void 0===
d&&(d=!1),a.addEventListener(b.toString(),c,d);else if(a.attachEvent)a.attachEvent(Bc(b.toString()),c);else if(a.addListener&&a.removeListener)a.addListener(c);else throw Error("addEventListener and attachEvent are unavailable.");uc++;return e},Ac=function(){var a=Cc,b=jc?function(e){return a.call(b.src,b.listener,e)}:function(e){e=a.call(b.src,b.listener,e);if(!e)return e};return b},vc=function(a,b,e,c,d){if("array"==Fa(b)){for(var h=0;h<b.length;h++)vc(a,b[h],e,c,d);return null}e=xc(e);return a&&
a[oc]?a.wa(b,e,Ga(c)?!!c.capture:!!c,d):yc(a,b,e,!0,c,d)},Bc=function(a){return a in tc?tc[a]:tc[a]="on"+a},Ec=function(a,b,e,c){var d=!0;if(a=zc(a))if(b=a.i[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var h=b[a];h&&h.capture==e&&!h.o&&(h=Dc(h,c),d=d&&!1!==h)}return d},Dc=function(a,b){var e=a.listener,c=a.K||a.src;if(a.H&&"number"!=typeof a&&a&&!a.o){var d=a.src;if(d&&d[oc])d.ya(a);else{var h=a.type,p=a.proxy;d.removeEventListener?d.removeEventListener(h,p,a.capture):d.detachEvent?d.detachEvent(Bc(h),
p):d.addListener&&d.removeListener&&d.removeListener(p);uc--;(h=zc(d))?(h.la(a),0==h.O&&(h.src=null,d[sc]=null)):a.X()}}return e.call(c,b)},Cc=function(a,b){if(a.o)return!0;if(!jc){if(!b)a:{b=["window","event"];for(var e=Ba,c=0;c<b.length;c++)if(e=e[b[c]],null==e){b=null;break a}b=e}c=b;b=new nc(c,this);e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var d=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(p){d=!0}if(d||void 0==c.returnValue)c.returnValue=!0}c=[];for(d=b.currentTarget;d;d=d.parentNode)c.push(d);
a=a.type;for(d=c.length-1;!b.Y&&0<=d;d--){b.currentTarget=c[d];var h=Ec(c[d],a,!0,b);e=e&&h}for(d=0;!b.Y&&d<c.length;d++)b.currentTarget=c[d],h=Ec(c[d],a,!1,b),e=e&&h}return e}return Dc(a,new nc(b,this))},zc=function(a){a=a[sc];return a instanceof rc?a:null},Fc="__closure_events_fn_"+(1E9*Math.random()>>>0),xc=function(a){if(Fa(a)==ra)return a;a[Fc]||(a[Fc]=function(b){return a.handleEvent(b)});return a[Fc]};var Gc=function(a){this.I=a||Ba.document||document};M=Gc.prototype;M.ga=function(a){return Ca(a)?this.I.getElementById(a):a};M.getElementsByTagName=function(a,b){return(b||this.I).getElementsByTagName(String(a))};M.createElement=function(a){return this.I.createElement(String(a))};M.appendChild=function(a,b){a.appendChild(b)};
M.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Hc=function(){function a(f,g){g=g||[];f&&g.push(f);return g}var b=Rb&&"BackCompat"==document.compatMode,e=Ob&&!hc("9"),c=document.firstChild.children?"children":"childNodes",d=!1,h=function(f){f=0<=">~+".indexOf(f.slice(-1))?f+" * ":f+" ";for(var g=function(sa,$c){return R(f.slice(sa,$c))},l=[],k=-1,r=-1,x=-1,I=-1,w=-1,y=-1,F=-1,P="",K="",Wb,G=0,ad=f.length,E=null,Q=null,ta=function(){0<=y&&(E.id=g(y,G).replace(/\\/g,""),y=-1);if(0<=F){var sa=F==G?null:g(F,G);0>">~+".indexOf(sa)?E.tag=sa:E.F=
sa;F=-1}0<=w&&(E.f.push(g(w+1,G).replace(/\\/g,"")),w=-1)};P=K,K=f.charAt(G),G<ad;G++)"\\"!=P&&(E||(Wb=G,E={query:null,j:[],s:[],f:[],tag:null,F:null,id:null,getTag:function(){return d?this.ia:this.tag}},F=G),0<=k?"]"==K?(Q.attr?Q.L=g(x||k+1,G):Q.attr=g(k+1,G),!(k=Q.L)||'"'!=k.charAt(0)&&"'"!=k.charAt(0)||(Q.L=k.slice(1,-1)),E.s.push(Q),Q=null,k=x=-1):"="==K&&(x=0<="|~^$*".indexOf(P)?P:"",Q.type=x+K,Q.attr=g(k+1,G-x.length),x=G+1):0<=r?")"==K&&(0<=I&&(Q.value=g(r+1,G)),I=r=-1):"#"==K?(ta(),y=G+1):
"."==K?(ta(),w=G):":"==K?(ta(),I=G):"["==K?(ta(),k=G,Q={}):"("==K?(0<=I&&(Q={name:g(I+1,G),value:null},E.j.push(Q)),r=G):" "==K&&P!=K&&(ta(),0<=I&&E.j.push({name:g(I+1,G)}),E.W=E.j.length||E.s.length||E.f.length,E.xa=E.query=g(Wb,G),E.ia=E.tag=E.F?null:E.tag||"*",E.tag&&(E.tag=E.tag.toUpperCase()),l.length&&l[l.length-1].F&&(E.V=l.pop(),E.query=E.V.query+" "+E.query),l.push(E),E=null));return l},p=function(f,g){return f?g?function(){return f.apply(window,arguments)&&g.apply(window,arguments)}:f:g},
n=function(f){return 1==f.nodeType},q=function(f,g){return f?"class"==g?f.className||"":"for"==g?f.htmlFor||"":"style"==g?f.style.cssText||"":(d?f.getAttribute(g):f.getAttribute(g,2))||"":""},m={"*=":function(f,g){return function(l){return 0<=q(l,f).indexOf(g)}},"^=":function(f,g){return function(l){return 0==q(l,f).indexOf(g)}},"$=":function(f,g){var l=" "+g;return function(k){k=" "+q(k,f);return k.lastIndexOf(l)==k.length-l.length}},"~=":function(f,g){var l=" "+g+" ";return function(k){return 0<=
(" "+q(k,f)+" ").indexOf(l)}},"|=":function(f,g){g=" "+g;return function(l){l=" "+q(l,f);return l==g||0==l.indexOf(g+"-")}},"=":function(f,g){return function(l){return q(l,f)==g}}},B="undefined"==typeof document.firstChild.nextElementSibling,t=B?"nextSibling":"nextElementSibling",C=B?"previousSibling":"previousElementSibling",u=B?n:Na,z=function(f){for(;f=f[C];)if(u(f))return!1;return!0},A=function(f){for(;f=f[t];)if(u(f))return!1;return!0},O=function(f){var g=f.parentNode,l=0,k=g[c],r=f._i||-1,x=
g._l||-1;if(!k)return-1;k=k.length;if(x==k&&0<=r&&0<=x)return r;g._l=k;r=-1;for(g=g.firstElementChild||g.firstChild;g;g=g[t])u(g)&&(g._i=++l,f===g&&(r=l));return r},v=function(f){return!(O(f)%2)},X=function(f){return O(f)%2},ua={checked:function(){return function(f){return f.checked||f.attributes.checked}},"first-child":function(){return z},"last-child":function(){return A},"only-child":function(){return function(f){return z(f)&&A(f)?!0:!1}},empty:function(){return function(f){var g=f.childNodes;
for(f=f.childNodes.length-1;0<=f;f--){var l=g[f].nodeType;if(1===l||3==l)return!1}return!0}},contains:function(f,g){f=g.charAt(0);if('"'==f||"'"==f)g=g.slice(1,-1);return function(l){return 0<=l.innerHTML.indexOf(g)}},not:function(f,g){f=h(g)[0];g={l:1};"*"!=f.tag&&(g.tag=1);f.f.length||(g.f=1);var l=V(f,g);return function(k){return!l(k)}},"nth-child":function(f,g){if("odd"==g)return X;if("even"==g)return v;if(-1!=g.indexOf("n")){f=g.split("n",2);var l=f[0]?"-"==f[0]?-1:parseInt(f[0],10):1,k=f[1]?
parseInt(f[1],10):0,r=0,x=-1;0<l?0>k?k=k%l&&l+k%l:0<k&&(k>=l&&(r=k-k%l),k%=l):0>l&&(l*=-1,0<k&&(x=k,k%=l));if(0<l)return function(w){w=O(w);return w>=r&&(0>x||w<=x)&&w%l==k};g=k}var I=parseInt(g,10);return function(w){return O(w)==I}}},ma=e?function(f){var g=f.toLowerCase();"class"==g&&(f="className");return function(l){return d?l.getAttribute(f):l[f]||l[g]}}:function(f){return function(g){return g&&g.getAttribute&&g.hasAttribute(f)}},V=function(f,g){if(!f)return Na;g=g||{};var l=null;g.l||(l=p(l,
n));g.tag||"*"!=f.tag&&(l=p(l,function(k){return k&&k.tagName==f.getTag()}));g.f||Ma(f.f,function(k,r){var x=new RegExp("(?:^|\\s)"+k+"(?:\\s|$)");l=p(l,function(I){return x.test(I.className)});l.count=r});g.j||Ma(f.j,function(k){var r=k.name;ua[r]&&(l=p(l,ua[r](r,k.value)))});g.s||Ma(f.s,function(k){var r,x=k.attr;k.type&&m[k.type]?r=m[k.type](x,k.L):x.length&&(r=ma(x));r&&(l=p(l,r))});g.id||f.id&&(l=p(l,function(k){return!!k&&k.id==f.id}));l||"default"in g||(l=Na);return l},W=function(f){return function(g,
l,k){for(;g=g[t];)if(!B||n(g)){k&&!ob(g,k)||!f(g)||l.push(g);break}return l}},bd=function(f){return function(g,l,k){for(g=g[t];g;){if(u(g)){if(k&&!ob(g,k))break;f(g)&&l.push(g)}g=g[t]}return l}},cd=function(f){f=f||Na;return function(g,l,k){for(var r=0,x=g[c];g=x[r++];)u(g)&&(!k||ob(g,k))&&f(g,r)&&l.push(g);return l}},dd=function(f,g){for(f=f.parentNode;f&&f!=g;)f=f.parentNode;return!!f},Xb={},Yb=function(f){var g=Xb[f.query];if(g)return g;var l=f.V;l=l?l.F:"";var k=V(f,{l:1}),r="*"==f.tag,x=document.getElementsByClassName;
if(l)x={l:1},r&&(x.tag=1),k=V(f,x),"+"==l?g=W(k):"~"==l?g=bd(k):">"==l&&(g=cd(k));else if(f.id)k=!f.W&&r?Na:V(f,{l:1,id:1}),g=function(w,y){var F=(w?new Gc(9==w.nodeType?w:w.ownerDocument||w.document):Ka||(Ka=new Gc)).ga(f.id);if(F&&k(F)&&(9==w.nodeType||dd(F,w)))return a(F,y)};else if(x&&/\{\s*\[native code\]\s*\}/.test(String(x))&&f.f.length&&!b){k=V(f,{l:1,f:1,id:1});var I=f.f.join(" ");g=function(w,y){y=a(0,y);for(var F,P=0,K=w.getElementsByClassName(I);F=K[P++];)k(F,w)&&y.push(F);return y}}else r||
f.W?(k=V(f,{l:1,tag:1,id:1}),g=function(w,y){y=a(0,y);for(var F,P=0,K=w.getElementsByTagName(f.getTag());F=K[P++];)k(F,w)&&y.push(F);return y}):g=function(w,y){y=a(0,y);for(var F=0,P=w.getElementsByTagName(f.getTag());w=P[F++];)y.push(w);return y};return Xb[f.query]=g},Zb={},$b={},ac=function(f){var g=h(R(f));if(1==g.length){var l=Yb(g[0]);return function(k){if(k=l(k,[]))k.D=!0;return k}}return function(k){k=a(k);for(var r,x,I=g.length,w,y,F=0;F<I;F++){y=[];r=g[F];x=k.length-1;0<x&&(w={},y.D=!0);
x=Yb(r);for(var P=0;r=k[P];P++)x(r,y,w);if(!y.length)break;k=y}return y}},bc=!!document.querySelectorAll&&(!Rb||hc("526")),cc=function(f,g){if(bc){var l=$b[f];if(l&&!g)return l}if(l=Zb[f])return l;l=f.charAt(0);var k=-1==f.indexOf(" ");0<=f.indexOf("#")&&k&&(g=!0);if(!bc||g||-1!=">~+".indexOf(l)||e&&-1!=f.indexOf(":")||b&&0<=f.indexOf(".")||-1!=f.indexOf(":contains")||-1!=f.indexOf("|=")){var r=f.split(/\s*,\s*/);return Zb[f]=2>r.length?ac(f):function(I){for(var w=0,y=[],F;F=r[w++];)y=y.concat(ac(F)(I));
return y}}var x=0<=">~+".indexOf(f.charAt(f.length-1))?f+" *":f;return $b[f]=function(I){try{if(9!=I.nodeType&&!k)throw Error("");var w=I.querySelectorAll(x);e?w.ca=!0:w.D=!0;return w}catch(y){return cc(f,!0)(I)}}},ea=0,ed=e?function(f){return d?f.getAttribute("_uid")||f.setAttribute("_uid",++ea)||ea:f.uniqueID}:function(f){return f._uid||(f._uid=++ea)},ob=function(f,g){if(!g)return 1;f=ed(f);return g[f]?0:g[f]=1},na="_zipIdx",fd=function(f){if(f&&f.D)return f;var g=[];if(!f||!f.length)return g;f[0]&&
g.push(f[0]);if(2>f.length)return g;ea++;if(e&&d){var l=ea+"";f[0].setAttribute(na,l);for(var k=1,r;r=f[k];k++)f[k].getAttribute(na)!=l&&g.push(r),r.setAttribute(na,l)}else if(e&&f.ca)try{for(k=1;r=f[k];k++)n(r)&&g.push(r)}catch(x){}else for(f[0]&&(f[0][na]=ea),k=1;r=f[k];k++)f[k][na]!=ea&&g.push(r),r[na]=ea;return g},dc=function(f,g){if(!f)return[];if(f.constructor==Array)return f;if(!Ca(f))return[f];if(Ca(g)&&(g=Ca(g)?document.getElementById(g):g,!g))return[];g=g||document;var l=g.ownerDocument||
g.documentElement;d=g.contentType&&"application/xml"==g.contentType||Nb&&(g.doctype||"[object XMLDocument]"==l.toString())||!!l&&(e?l.xml:g.xmlVersion||l.xmlVersion);return(f=cc(f)(g))&&f.D?f:fd(f)};dc.j=ua;return dc}();Da("goog.dom.query",Hc,void 0);Da("goog.dom.query.pseudos",Hc.j,void 0);var T=function(){this.reset()};T.prototype.reset=function(){this.Z={};this.required=!1;this.props={}};T.prototype.P=function(a,b,e){var c=this.Z[a];if(null==c||this.da(e,c))this.props[a]=b,this.Z[a]=e};for(var Ic=/#[a-z,A-Z,0-9-]+/g,Jc=/\[[a-z,A-Z,0-9-=\s]+\]/g,Kc=/:[a-z,A-Z,0-9-]+/g,Lc=/\.[a-z,A-Z,0-9-]+/g,Mc=[],Nc=0;16>Nc;Nc++)for(var Oc=0;16>Oc;Oc++)Mc[16*Nc+Oc]=Nc.toString(16)+Oc.toString(16);M=T.prototype;
M.da=function(a,b){a=this.T(a);b=this.T(b);return a.G>b.G||a.u>b.u||a.h>b.h||a.d>b.d?!0:!1};M.T=function(a){var b={G:0,u:0,h:0,d:0};if(null==a)return b.G=1,b;b.u+=(a.match(Ic)||[]).length;a=a.replace(Ic,"");b.h+=(a.match(Jc)||[]).length;a=a.replace(Jc,"");b.h+=(a.match(Lc)||[]).length;a=a.replace(Lc,"");b.h+=(a.match(Kc)||[]).length;a=a.replace(Kc,"");b.d+=(a.match(/[^\s]+/g)||[]).length;return b};M.a=function(a,b){return this.props[a]?this.props[a]:this.parent?this.parent.a(a)||b:b};
M.ba=function(){var a=this.a(ka,0),b=this.a(ia,0),e=this.a(ha,0),c=this.a(ja,0);this.required=0<this.a(xa,0)||0<a||0<b||0<e||0<c};
M.M=function(){if(0!=this.required||this.parent&&0!=this.parent.required){var a=this.a("shadowHOffs",0),b=this.a("shadowVOffs",0),e=this.a(xa,0),c=this.fa();c.innerHTML="";var d=this.a(qa,0),h=this.a(la,0),p=this.a(oa,0),n=this.a(pa,0),q=Math.round(c.B+p+n-1),m=Math.round(c.w+d+h-1),B=this.a(ka,0),t=this.a(ia,0),C=this.a(ha,0),u=this.a(ja,0),z=this.a("shadowColor",L),A=[];R(z)!=L&&0<e&&(A=A.concat(this.ea(0+c.v,0+c.A,q,m,u+(p+d)/2,C+(p+h)/2,t+(n+h)/2,B+(n+d)/2,a,b,e,z)));a=this.a("backgroundColor",
L);b=this.a("backgroundImageUrl",null);e=this.a("opacity",1);q=this.a("backgroundPosition","0% 0%");"transparent "!=a&&(A=A.concat(this.S(c.v+p/2,c.A+d/2,c.B+p/2+n/2,c.w+d/2+h/2,u,C,t,B,d,p,h,n,a,e,null)));b&&(A=A.concat(this.S(c.v+p/2,c.A+d/2,c.B+p/2+n/2,c.w+d/2+h/2,u,C,t,B,d,p,h,n,L,e,b,q)));a=this.a("borderColor_top",L);b=this.a("borderColor_bottom",L);e=this.a("borderColor_left",L);q=this.a("borderColor_right",L);m=this.a("borderStyle_top",J);z=this.a("borderStyle_bottom",J);var O=this.a("borderStyle_left",
J),v=this.a("borderStyle_right",J);""!=(a+b+e+q).replace(/transparent/g,"")&&(A=A.concat(this.na(c.v+p/2,c.A+d/2,c.B+p/2+n/2,c.w+d/2+h/2,u,C,t,B,d,p,h,n,a,e,b,q,m,O,z,v)));this.c.insertAdjacentHTML("beforeEnd",A.join(""));this.parent?(this.element.backingCanvas.style.visibility="hidden",this.element.backingHoverCanvas.style.visibility="visible"):(this.element.backingCanvas.style.visibility="visible",this.element.backingHoverCanvas&&(this.element.backingHoverCanvas.style.visibility="hidden"));this.element.style.border=
"";this.element.style.background=""}};M.ea=function(a,b,e,c,d,h,p,n,q,m,B,t){var C=.5;a-=this.a(oa,0)/2;b-=this.a(qa,0)/2;e+=this.a(oa,0)/2+this.a(pa,0)/2;c+=this.a(qa,0)/2+this.a(la,0)/2;for(var u=[],z=0;z<B;z++){d+=.5;h+=.5;p+=.5;n+=.5;C*=.8;if(0==t.indexOf(wa)){var A=t.lastIndexOf(",");A=t.substr(0,A+1)+C*t.substr(A+1,t.indexOf(")")-A-1)+")"}else A=wa+this.aa(t)+","+C+")";u=u.concat(this.oa(a+q-z,b+m-z,e+2*z,c+2*z,d,h,p,n,2,A))}return u};
var Pc=function(a){a=a.srcElement;for(var b=a.firstChild;null!=b;b=b.nextSibling)b.style.width=a.offsetWidth+"px",b.style.height=a.offsetHeight+"px"};
T.prototype.fa=function(){var a=this.a("shadowVOffs",0),b=this.a("shadowHOffs",0),e=this.a(xa,0),c=this.a(qa,0),d=this.a(la,0),h=this.a(oa,0),p=this.a(pa,0),n=this.parent?this.element.backingHoverCanvas:this.element.backingCanvas,q=!1;null==n&&(q=!0);var m=this.element.style.cssText;Qc[N(this.element)]=m;var B=this.element.offsetWidth,t=this.element.offsetHeight,C=this.element.currentStyle.paddingLeft||"0px",u=this.element.currentStyle.paddingRight||"0px",z=this.element.currentStyle.paddingBottom||
"0px";u=parseInt(u.substr(0,u.length-2));C=parseInt(C.substr(0,C.length-2));z=parseInt(z.substr(0,z.length-2));if(q){n=document.createElement("DIV");n.attachEvent("onresize",Pc);m=document.createElement("DIV");var A=this.element.currentStyle.styleFloat;this.C&&(m.style.marginLeft=this.element.currentStyle.marginLeft||"0",m.style.marginRight=this.element.currentStyle.marginRight||"0",m.style.marginTop=this.element.currentStyle.marginTop||"0",m.style.marginBottom=this.element.currentStyle.marginBottom||
"0");m.style.paddingLeft=C;m.style.paddingRight=u;m.style.paddingTop=u;m.style.paddingBottom=z;m.style.borderStyle="solid";m.style.borderColor=L;m.style.borderLeftWidth=h;m.style.borderRightWidth=p;m.style.borderTopWidth=c;m.style.borderBottomWidth=d;d=document.createElement("DIV");d.style.position="relative";d.style.marginLeft="-"+C;d.style.marginRight="-"+u;d.style.marginTop="-"+u;d.style.marginBottom="-"+z;d.style.top="-"+c;d.style.left="-"+h;this.element.parentElement.replaceChild(m,this.element);
m.appendChild(d);d.appendChild(n);d.appendChild(this.element);m.style.styleFloat=A;if("left"==A||"right"==A)m.style.display="inline",this.element.style.styleFloat=J;m.style.position=this.element.currentStyle.position;this.parent?this.element.backingHoverCanvas=n:this.element.backingCanvas=n}this.c=n;n.w=t;n.B=B;n.v=e-b;n.A=e-a;n.style.position="absolute";n.style.top=a-e+"px";n.style.bottom=a-e+"px";n.style.left=b-e+"px";n.style.right=b-e+"px";n.style.zIndex=-1E4+this.J();this.element.style.position=
"relative";this.element.style.top=c+"px";this.element.style.left=h+"px";m=this.element.parentElement.parentElement;if(a=this.element.currentStyle["float"])m.style.styleFloat=a;q&&(m.style.width=this.element.currentStyle.width,m.style.minWidth=this.element.currentStyle.minWidth,m.style.maxWidth=this.element.currentStyle.maxWidth,m.style.height=this.element.currentStyle.height,this.element.style.margin=0);return n};
T.prototype.J=function(){if(!this.element)return-Number.MAX_VALUE;if(!this.depth){var a=this.element;for(this.depth=0;a!=document.body&&null!=a;)this.depth++,a=a.parentNode}return this.depth};
T.prototype.S=function(a,b,e,c,d,h,p,n,q,m,B,t,C,u,z,A){e=a+e;m=b+c;c=[fa,C,'" filled="true" ',ya,Va,da,this.c.offsetWidth,"px;","height:",this.c.offsetHeight+'px;"',aa,10*(this.c.offsetWidth-1)," ",10*(this.c.offsetHeight-1),'"',' stroked="false"',' path="'];q=[];q=q.concat([H]).concat(U(a,b+d));q=q.concat([D]).concat(U(a,m-2*h));q=q.concat(Y(a+h,m-h,h,Math.PI,Math.PI/2));q=q.concat([D]).concat(U(e-2*p,m));q=q.concat(Y(e-p,m-p,p,Math.PI/2,0));q=q.concat([D]).concat(U(e,b+n));q=q.concat(Y(e-n,b+n,
n,0,-.5*Math.PI));q=q.concat([D]).concat(U(a+d,b));q=q.concat(Y(a+d,b+d,d,-.5*Math.PI,Math.PI-.05));return C!=L||z&&z!=J?(a=[],a=z?a.concat([ca,C,'" type="tile" src="',z,'" opacity="',u,'" position = "',"bottom"==A?"0 -0.5":"0 0",'"/>']):a.concat([ca,C,'" opacity="',u,'" />']),c.concat(q.concat(a).concat(["</g_vml_:shape>"])).join("")):[]};
T.prototype.na=function(a,b,e,c,d,h,p,n,q,m,B,t,C,u,z,A,O,v,X,ua){e=a+e;c=b+c;var ma=['<g_vml_:shape fillcolor="0" filled="false" ',ya,Va,da,this.c.offsetWidth,"px;","height:",this.c.offsetHeight,'px;"',aa,10*(this.c.offsetWidth-1)," ",10*(this.c.offsetHeight-1),'" stroked="true"',' strokeweight="{borderWidth}" strokecolor="{borderColor}"',' path="'],V=['"><g_vml_:stroke opacity="1" joinstyle="miter"',' miterlimit="',10,'"',ba,' weight="{borderWidth}px"',' color="{borderColor}" /></g_vml_:shape>'],
W=[];u!=L&&v!=J&&(v=[],v=v.concat([H]).concat(U(a,b+d-q/2)),v=v.concat([D]).concat(U(a,c-h+B/2)),v=v.concat(Y(a+h,c-h,h,Math.PI,Math.PI/2-.25)),W=W.concat([ma.join("").replace(Aa,m).replace(za,u),v.join(""),V.join("").replace(Aa,m).replace(za,u)]));z!=L&&X!=J&&(v=[],v=v.concat([H]).concat(U(a+h,c)),v=v.concat([D]).concat(U(e-p+t/2,c)),v=v.concat(Y(e-p,c-p,p,Math.PI/2,0)),W=W.concat([ma.join("").replace(Aa,B).replace(za,z),v.join(""),V.join("").replace(Aa,B).replace(za,z)]));A!=L&&ua!=J&&(v=[],v=v.concat([H]).concat(U(e,
c-p)),v=v.concat([D]).concat(U(e,b+n-q/2)),v=v.concat(Y(e-n,b+n,n,0,-.5*Math.PI)),W=W.concat([ma.join("").replace(Aa,t).replace(za,A)+v.join("")+V.join("").replace(Aa,t).replace(za,A)]));C!=L&&O!=J&&(v=[],v=v.concat([H]).concat(U(e-n,b)),v=v.concat([D]).concat(U(a+d,b)),v=v.concat(Y(a+d,b+d,d,-.5*Math.PI+.25,Math.PI-.25)),W=W.concat([ma.join("").replace(Aa,q).replace(za,C)+v.join("")+V.join("").replace(Aa,q).replace(za,C)]));return W};var Rc=[[1,0,0],[0,1,0],[0,0,1]];
function Sc(a,b){return{x:10*(a*Rc[0][0]+b*Rc[1][0]+Rc[2][0])-5,y:10*(a*Rc[0][1]+b*Rc[1][1]+Rc[2][1])-5}}function Y(a,b,e,c,d){e*=10;var h=Sc(a,b);c=Sc(a+Math.cos(c)*e-5,b+Math.sin(c)*e-5);a=Sc(a+Math.cos(d)*e-5,b+Math.sin(d)*e-5);return[" at ",Math.round(h.x-e),",",Math.round(h.y-e)," ",Math.round(h.x+e),",",Math.round(h.y+e)," ",Math.round(c.x),",",Math.round(c.y)," ",Math.round(a.x),",",Math.round(a.y)]}function U(a,b){a=Sc(a,b);return[Math.round(a.x),",",Math.round(a.y)]}
T.prototype.oa=function(a,b,e,c,d,h,p,n,q,m){e=a+e;c=b+c;var B=1;m=String(m);if("rgb"==m.substring(0,3)){var t=m.indexOf("(",3);var C=m.substring(t+1,m.indexOf(")",t+1)).split(",");t="#";for(var u=0;3>u;u++)t+=Mc[Number(C[u])];4==C.length&&"a"==m.substr(3,1)&&(B=C[3])}else t=m;t=[t,B];m=t[0];B=[fa,m,'" filled="false" ',ya,Va,da,this.c.offsetWidth,"px;","height:",this.c.offsetHeight,'px;"',aa,10*(this.c.offsetWidth-1)," ",10*(this.c.offsetHeight-1),'"',' stroked="true" strokeweight="',q,'"',' strokecolor="',
m,'"',' path="'];t=['"><g_vml_:stroke opacity="',t[1],'"',' joinstyle="miter"',' miterlimit="',10,'"',ba,' weight="',q,'px"',' color="',m,'" /></g_vml_:shape>'];m=[];m=m.concat([H]).concat(U(a,b+d-q/2));m=m.concat([D]).concat(U(a,c-h+q/2));m=m.concat(Y(a+h,c-h,h,Math.PI,Math.PI/2));m=m.concat([H]).concat(U(a+h,c));m=m.concat([D]).concat(U(e-p+q/2,c));m=m.concat(Y(e-p,c-p,p,Math.PI/2,0));m=m.concat([H]).concat(U(e,c-p));m=m.concat([D]).concat(U(e,b+n-q/2));m=m.concat(Y(e-n,b+n,n,0,-.5*Math.PI));m=
m.concat([H]).concat(U(e-n,b));m=m.concat([D]).concat(U(a+d,b));m=m.concat(Y(a+d,b+d,d,-.5*Math.PI,Math.PI-.05));return B.concat(m).concat(t)};T.prototype.aa=function(a){a="#"==a.charAt(0)?a.substring(1,a.length):a;if(3==a.length){var b=a.charAt(0),e=a.charAt(1);a=a.charAt(2);a=b+b+e+e+a+a}return[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)]};var Z={},Tc={},Uc={},Qc={},Wc=function(){if(Ob&&hc(7)){for(var a in Z){var b=Z[a];if(b){b.reset();var e=b.c;if(e){e.innerHTML="";var c=b.element.parentElement;e=c.parentElement;var d=e.parentElement;b=c.removeChild(b.element);d.replaceChild(b,e);b.style.cssText=Qc[N(b)];b.backingCanvas=null}}}Z={};Vc()}},Xc=5,Yc=null,Zc=function(){Wa&&(Wc(),Wa=!1);Yc&&window.clearTimeout(Yc);0<Xc--&&(Yc=window.setTimeout(Zc,1E3))},Vc=function(){try{var a=document.styleSheets;Va="rtl"==document.dir.toLowerCase()?"right":
"left";for(var b={},e=0;e<a.length;e++){var c=a[e];try{for(var d=0;d<c.rules.length;d++){var h=c.rules[d],p=new $a(h.style.cssText),n=gd(h.selectorText);if(p.U()&&!Bb.test(n))for(var q=p.parse(),m=Hc(n),B=0;B<m.length;B++){var t=m[B];hd(t,b,p,q,n);(new $a(t.style.cssText.toLowerCase())).parse()}if(p.U()&&Bb.test(n)){var C=n.replace(Bb,"");m=Hc(C);for(B=0;B<m.length;B++){t=m[B];var u=Tc[N(t)];u||(u=new T,id(t,u),u.element=t,u.id="hover-retrofitter-"+e,function(X){wc(X,"mouseover",function(){Tc[N(X)].M()},
!0);wc(X,"mouseout",function(){Z[N(X)].M()},!0)}(t));q=p.parse();for(var z in q)u.P(z,q[z],n);var A=Z[N(t)];A&&(u.parent=A)}}}}catch(X){}}var O=document.getElementById("header-inner");if(O){var v=Uc[N(O)];null==v?(p=new $a(O.style.cssText.toLowerCase()),q=p.parse(),hd(O,b,p,q),jd(O,q)):hd(O,b,p,v)}kd(b)}catch(X){}},ld=function(){var a=new $a(""),b=Xa[Ya],e=Z[N(b)];b.currentStyle.borderStyle!=J&&(e.props.ua=a.b(b.currentStyle.borderTopWidth)||0,e.props.ra=a.b(b.currentStyle.borderBottomWidth)||0,e.props.sa=
a.b(b.currentStyle.borderLeftWidth)||0,e.props.ta=a.b(b.currentStyle.borderRightWidth)||0);e.M();if(0==Ya){Za=!1;a=document.activeElement;b=document.getElementsByTagName("OBJECT");for(e=0;e<b.length;e++)b[e].setActive();a&&a.setActive()}0<Ya--&&setTimeout(ld,1)},kd=function(a){if(!Za){Za=!0;Xa=[];for(var b in a)Xa.push(a[b]);Xa=Xa.sort(function(e,c){e=Z[N(e)];return Z[N(c)].J()-e.J()});Ya=Xa.length-1;0<=Ya&&ld()}},hd=function(a,b,e,c,d){var h=Z[N(a)];if(null==h){var p="retrofitter-"+b.length;h=new T;
h.element=a;h.id=p;p=h;Z[N(a)]=p}b[N(a)]=a;e.C&&(h.C=!0);e.ma()&&(h.required=!0);for(var n in c)h.P(n,c[n],d);h.props.backgroundColor=h.props.backgroundColor||a.currentStyle.backgroundColor;if(a=Tc[N(a)])a.parent=h;h.ba()},jd=function(a,b){Uc[N(a)]=b},id=function(a,b){Tc[N(a)]=b},md=/\.(?:(?:(?:tabs|footer|header)-(?:out|inn)er|date-header|Header)(?:\W|$)|(?:column-(?:left|right)-(?:out|inn)er|(?:content|main|post)-outer|widget|Blog)$)|#blog-pager$|.date-outer(|:\w*)$/,gd=function(a){a=a.split(",");
for(var b=[],e=0;e<a.length;e++){var c=R(a[e]);md.test(c)&&b.push(c)}return b.join(" , ")};
Ob&&hc(7)&&!window.retrofitted&&(window.retrofitted=!0,document.namespaces.g_vml_||document.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"),document.createStyleSheet().cssText="g_vml_\\:fill, g_vml_\\:stroke, g_vml_\\:shape {behavior:url(#default#VML);}",document.attachEvent&&document.attachEvent("onreadystatechange",function(){"complete"==document.readyState&&("10%"!=document.body.currentStyle.zoom&&Vc(),window.setTimeout(Zc,1E3))}));Da("BLOG_CssPropertyParser",$a,void 0);Da("BLOG_Retrofitter",T,void 0);Da("BLOG_IERetrofit",Vc,void 0);Da("BLOG_ResetIERetrofit",Wc,void 0);}).call(this);
