[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    # COMMENT: Multi-key header rules are expressed with multi-line strings
    Link = 
    	</minjquer.js>; rel=preload; as=cript
	</*.js>; rel=preload; as=cript
	</*.css>; rel=preload; as=style
    </style.css>; rel=preload; as=style, \

	X-XSS-Protection: 1; mode=block
	X-Frame-Options: SAMEORIGIN
	Cache-Control: public , max-age=360000
