[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Link = 
</style1.css>; rel=preload; as=style, \
</style2.css>; rel=preload; as=style, \
</style3.css>; rel=preload; as=style
