[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
Link: </style.css>; rel=preload; as=style, </main.js>; rel=preload; as=script, </image.jpg>; rel=preload; as=image
